export enum ItemType {
    WEAPON_LONG_RANGE = "WEAPON_LONG_RANGE",
    WEAPON_MELEE = "WEAPON_MELEE",
    ARMOR = "ARMOR",
    CONSUMABLES = "CONSUMABLES",
    MAGICAL = "MAGICAL",
    TRANSPORT = "TRANSPORT",
    KEYS = "KEYS",
}