export enum Locations {
    ENTRANCE = "ENTRANCE",
    MAIN_TUNNEL = "MAIN_TUNNEL",
    CRYPT = "CRYPT",
    LIBRARY = "LIBRARY",
    MIRROR_CHAMBER = "MIRROR_CHAMBER",
    GUARDIAN_HALL = "GUARDIAN_HALL",
    HEART_OF_CITY = "HEART_OF_CITY"
}